#!/usr/bin/env bash
# Prints 1 to 20 and a little more detail for bad days
count=1
while [ "$count" -le 20 ]
do
    echo "$count"
    case "$count" in
        4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
    esac
    ((count++))
done
